version: '3'
services:  
  mongo-db:
    container_name: mongo-db
    image: mongo:5.0
    volumes:
      - ./mongo-db-backup:/backup
    ports:
      - 27017:27017

  study-buddy-api:
    container_name: spirit-library
    build: ./study-buddy-api
    environment:
      - DATABASE_URL='mongodb://mongo-db:27017/'
      - ADDRESS=localhost
      - PORT=3000
    deploy:
      restart_policy:
        delay: 3s
    depends_on:
      - mongo-db
    links:
      - mongo-db
    ports:
      - 3000:3000
    volumes:
      - ./study-buddy-api:/usr/src/app

  # tunnel-vision:
  #   container_name: tunnel-vision
  #   build: ./tunnel-vision
  #   environment:
  #     - API_URL='study-buddy-api:3000/'
  #   deploy:
  #     restart_policy:
  #       condition: on-failure
  #       delay: 5s
  #       window: 120s
  #   depends_on:
  #     - mongo-db
  #   links:
  #     - tunnel-vision
  #   ports:
  #     - 3001:3001
  #   volumes:
  #     - ./tunnel-vision:/usr/src/app
