services: 
  mongo-db:
    build:
      context: ./mongo
      dockerfile: MongoDB.Dockerfile
    command: --auth
    container_name: mongo-db
    environment:
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/database_username
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/database_password
    volumes:
      - ./mongo/mongo-db-backup:/backup
      - ./mongo/database:/data/db
    ports:
      - 27017:27017
    secrets:
      - database_username
      - database_password

  study-buddy-api:
    container_name: spirit-library
    build: 
      context: ./study-buddy-api
      dockerfile: Prod.Dockerfile
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
    depends_on:
      - mongo-db
    env_file:
      - .env
    links:
      - mongo-db
    ports:
      - 3002:3002
    volumes:
      - ./study-buddy-api:/usr/src/app

  tunnel-vision:
    container_name: tunnel-vision
    build: 
      context: ./tunnel-vision
      dockerfile: Prod.Dockerfile
    environment:
      API_URL: 'study-buddy-api:3002/'
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 120s
    links:
      - study-buddy-api
    ports:
      - 3001:3000
    volumes:
      - ./tunnel-vision:/usr/src/app

secrets:
  database_password:
    file: database_password.txt
  database_username:
    file: database_username.txt
