version: '3.3'
services: 
  mongo-db:
    command: --auth
    container_name: mongo-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: Admin
      MONGO_INITDB_ROOT_PASSWORD: AdM1n
    image: mongo:5.0
    volumes:
      - ./mongo-db-backup:/backup
    ports:
      - 27017:27017

  study-buddy-api:
    container_name: spirit-library
    build: ./study-buddy-api
    environment:
      - DATABASE_URL=mongodb://Admin:AdM1n@mongo-db:27017/
      - DATABASE_NAME=StudyLog
      - ADDRESS=localhost
      - PORT=3002
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
    depends_on:
      - mongo-db
    links:
      - mongo-db
    ports:
      - 3002:3002
    volumes:
      - ./study-buddy-api:/usr/src/app

  tunnel-vision:
    container_name: tunnel-vision
    build: ./tunnel-vision
    environment:
      - API_URL='study-buddy-api:3000/'
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 120s
    links:
      - study-buddy-api
    ports:
      - 3001:3000
    volumes:
      - ./tunnel-vision:/usr/src/app
